# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tenders-ebiznes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bc7529efc5e64c67a58486f146a4b980 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_dd85f15e23984f4096635ab3bf130e64 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_bc7529efc5e64c67a58486f146a4b980 }}/Janszczyrek/tender:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tenders-ebiznes'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_03d758985aa84e83969a72624acfb5ec }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_bc7529efc5e64c67a58486f146a4b980 }}/Janszczyrek/tender:${{ github.sha }}'